import Head from 'next/head'
import classes from 'src/styles/Home.module.css'
import { Header } from 'src/components/Header'
import { Main } from 'src/components/Main'
import { useCallback, useEffect, useState } from 'react'

const  About = () => {
  const [count, setCount] = useState(0)
  const [text, setText] = useState('')
  const [array, setArray] = useState([])

  const countUp = useCallback(() => {
    setCount(prevCount => prevCount + 1)
  }, [])
  const countDown = useCallback(() => {
    setCount(prevCount => prevCount - 1)
  }, [])

  const handleChangeText = useCallback((e) => {
    // スペースの入力を制限
    setText(e.target.value.trim())
  }, [])

  const handleAddArray = useCallback(() => {
    setArray((prevArray) => {
      if(prevArray.some(item => item === text)) {
        alert("Already exist!")
        return prevArray
      }
      return [...prevArray, text]
    })
  }, [text])

  return (
    <>
      <Header/>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <h1>{count}</h1>
      <button onClick={countUp}>
        Up!
      </button>
      <button onClick={countDown}>
        Down!
      </button>

      <input type="text" value={text} onChange={handleChangeText}/>

      <button onClick={handleAddArray}>
        AddItem!!
      </button>
      <ul>
        {array.map((item) => {
          return <li key={item}>{item}</li>
        })}
      </ul>
      <Main/>
    </>
  )
}
export default About
