import Head from 'next/head'
import classes from 'src/styles/Home.module.css'
import { Header } from 'src/components/Header'
import { Main } from 'src/components/Main'
import { useCallback, useEffect, useState } from 'react'
import { useCounter } from 'src/hooks/useCounter'
import { useInputArray } from 'src/hooks/useInputArray'

export default function Home() {
  const { text, array, handleChangeText, handleAddArray } = useInputArray()
  const { count, countUp, countDown } = useCounter()

  useEffect(() => {
    console.log("mount", count)
    return () => {
      console.log("unmount", count)
    }
  }, [count])

  return (
    <>
      <Header/>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <h1>{count}</h1>
      <div>
        <button onClick={countUp}>
          Up!
        </button>
        <button onClick={countDown}>
          Down!
        </button>
      </div>

      <div>
        <input type="text" value={text} onChange={handleChangeText}/>
        <button onClick={handleAddArray}>
          AddItem!!
        </button>
        <ul>
          {array.map((item) => {
            return <li key={item}>{item}</li>
          })}
        </ul>
      </div>
      <Main/>
    </>
  )
}
