import Head from 'next/head'
import classes from '../styles/Home.module.css'
import { Links } from '../components/Links'
import { Headline } from '../components/Headline'
import { CenterLogos } from '../components/CenterLogos'
import { Header } from '../components/Header'

export default function Home() {
  return (
    <>
      <Header/>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classes.main}>
        <Headline/>
        <CenterLogos/>
        <Links/>
      </main>
    </>
  )
}
